### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by LappleApple** [zalando/spring-boot-etcd#1]
Hi -- this looks useful to non-Zalandos; is it? And is it in use internally?

**Comment by MALPI** [comment]
Might be, yes. If externals use our Cassandra-Appliance and have to resolve the contactnode via etcd.

I am not sure if the spring default lib also supports datastax driver version 3, which this auto configuration does.

It's used by us (Schotter) and I think also by Team Zaster.

**Comment by MALPI** [comment]
It's used by https://github.com/zalando/spring-boot-cassandra
